### ISSUE TITLE
Add author parameter

### ISSUE THREAD

**Issue by chellman** [barryhughes/event-rocket#18]
This is a nice plugin - thanks for writing it.  It would be nice to be able to pull the events by the user who posted them.  I don't see an author parameter available right now, but that was would really helpful for a site I'm working on.

I'm going to see what I can do on my own, but I'm not familiar with the event calendar's API, so figured I'd post the issue first. If I can turn this into a PR, I will.

**Comment by barryhughes** [comment]
Hi @chellman - just to clarify, do you mean within the placeholder system, ie:

```
[event_embed]
    {title} on {start_date} was listed by {author}
[/event_embed]
```

Or somewhere else?

**Comment by barryhughes** [comment]
... If so, I just added it! Let me know if that doesn't work for you/you need it someplace else etc.

Thanks :-)

**Comment by chellman** [comment]
Hey @barryhughes,

That's helpful too, but I'm looking for a way to list events that were posted by Author X.  So like this for events posted by the author 2.

[event_embed author="2"]
    {title} on {start_date} was listed by {author}
[/event_embed]

**Comment by barryhughes** [comment]
Ah hah! I certainly misunderstood.

Seems reasonable enough and it might be nice to bake this in - note that you can already add new shortcode attributes and change the query to implement things like this.

See: https://wordpress.org/support/topic/offset-posts-events

Custom code can access the shortcode params and change the query to suit, essentially, if you need something in place in the short term :-)
