### ISSUE TITLE
Add count limiter to [embed_venue], [embed_organizer], [embed_event] as available in [event_rocket_calendar]

### ISSUE THREAD

**Issue by Sven-WEBDESIGN** [barryhughes/event-rocket#25]
Hello,

Could you confirm that the count limiter property "count" is only available in the [event_rocket_calendar]? If so, could you add it for the other embeds shortcodes: [embed_venue], [embed_organizer], [embed_event]?

**Comment by barryhughes** [comment]
Hi @Sven-WEBDESIGN,

All of the `[*_embed]` shortcodes support a `limit` property:

`[event_embed category="foo" limit="10"]`

`[event_rocket_calendar]` is slightly different in that the equivalent to `limit` is named `count` - this is a little inconsistent, but reflects the fact that the underlying code in the matching Events Calendar PRO widget looks for a widget setting with that name.

https://github.com/barryhughes/event-rocket/wiki/Embed-Events
