### ISSUE TITLE
Feature Request: iCal Formatting with Embed Event Support

### ISSUE THREAD

**Issue by barryhughes** [barryhughes/event-rocket#27]
This is quite a good idea and actually could provide a framework for other things, like generating download-in-csv-format links and so on:

https://wordpress.org/support/topic/request-ics-format-shortcode

**Comment by louking** [comment]
Cool! I have a use case for csv format, too!

**Comment by barryhughes** [comment]
This should officially roll out as part of the 3.0 release. Some example usage:

``` html
[eventrocket_csv_link from="today" to="+1 month"] Download events in CSV format! [/eventrocket_csv_link]
```

Ditto for ical - but the shortcode in that case is:

``` html
[eventrocket_ical_link]
```

Supported params:

* `event` (one or more event IDs/slugs)
* `from`
* `to`
* `category` or `categories`
* `tag` or `tags`

This is a subset of those supported by `[event_embed]` which is indeed used "under the hood" to service these requests.

**Comment by louking** [comment]
Thanks, Barry -- I hope to check this out soon

**Comment by louking** [comment]
Looks like my event rockets plugin did not update automatically -- do I need to take some action?
