### ISSUE TITLE
Feature Request: Display Venues by Location

### ISSUE THREAD

**Issue by JamesWemyss** [barryhughes/event-rocket#28]
Would be great to be able to show a list of venues by the state/province

**Comment by barryhughes** [comment]
Examples (should be generally available when 3.0 is released):

*All venues in a particular state*

``` html
<!-- all venues in California -->
[embed_venue state="CA"]
```

*Non-US states/provinces*

``` html
<!-- must match the free text state/province field -->
[embed_venue province="Queensland, NSW"]
```

*Postal code matches*

``` html
<!-- matches all postcodes containing 902, ie 90210, 90211, 90212, ... -->
[embed_venue zip="902"]
```
*Combined city and postal code filter*

``` html
<!-- all venues in London with an SW (South West) postal code -->
[embed_venue city="London" postcode="SW"]
```

Note that these parameters are case sensitive, ie "ca" and "CA" are not the same thing.
