### ISSUE TITLE
Event Offset Option

### ISSUE THREAD

**Issue by PthPndr** [barryhughes/event-rocket#31]
As per [this] (https://wordpress.org/support/topic/upcoming-events-9?replies=4#post-7061973) discussion it would be great if you could add an option to allow the individual selection of upcoming events.

**Comment by barryhughes** [comment]
Note to self: offset and paging capabilities would greatly enhance the event-embed system's ability to be used for specialist/custom views (as well as helping with the use case linked to above).

**Comment by psteinweber** [comment]
Just came here to +1 this request. Would be amazing to see this!

**Comment by barryhughes** [comment]
Commit 3f4497db66774a1859e24081b54713708595d19d adds initial offset and pagination support:

``` html
<!-- skip a specific number of posts -->
[event_embed offset="7"]
```

It also adds pagination if you prefer that to trying to calculate offsets:

``` html
<!-- specify a page of results -->
[event_embed page="4"]
```

These can of course be combined with `limit` if you want something other than the default posts-per-page value:

``` html
<!-- specify a page of results (where each page contains 6 events) -->
[event_embed page="4" limit="6"]
```

Lastly, the page parameter can be set automatically, ie:

``` html
<!-- specify a page of results -->
[event_embed page="auto"]
```

Generally speaking - unless further tweaks are made - this is only useful if the shortcode is embedded in a page. Assuming it is, though, then default WP rewrite rules mean URLs like _/page-slug/page/3/_ are possible and the shortcode will adopt the same page number automatically.

For a sneak preview and to test this work before the next official release goes out on wordpress.org, please use [this build](https://github.com/barryhughes/event-rocket/archive/3f4497db66774a1859e24081b54713708595d19d.zip) (or just the latest code from the `develop` branch) and let me know of any difficulties as it has only had the lightest possible testing so far.

**Comment by psteinweber** [comment]
Thanks Barry - tested it and seems to work great so far!

**Comment by PthPndr** [comment]
Same here. Only had a slight chance to play with it so far but it appears to be working as expected. Thanks again for adding this feature!

**Comment by barryhughes** [comment]
Thanks for the feedback guys, much appreciated.
