### ISSUE TITLE
Duplicate Tickets (tickets addon)

### ISSUE THREAD

**Issue by adaptifyDesigns** [barryhughes/event-rocket#34]
I love the duplicate event functionality that Event Rocket provides. It would be so cool if when you duplicated an event, any tickets (created by the WooTickets or any other Tickets addon) were also duplicated for that event. Currently they do not :-(

Would this be possible?

Thanks!

**Comment by barryhughes** [comment]
Hi @adaptifyDesigns - that's a fantastic idea!

Let's use WooCommerce Tickets as our sample ticketing addon: right now, each ticket is actually a regular WooCommerce product that has been linked to the event. What's the desirable behaviour here:

1. Do we link the duplicated event with the very same tickets (products) that already exist?
2. Or, do we duplicate the tickets (products) and then link them with the duplicated event?
3. Do we offer a choice of either these things?

(Though I'm using WooCommerce Tickets in my example, the same thing basically holds true for the related Shopp, WP eCommerce and EDD addons - but let's focus on Woo for the moment.)

The first option is certainly the easiest to implement but my instinct tells me the second is more desirable ... might there be a case for the third? ... as someone who actively wants to see this, what do you think?

**Comment by adaptifyDesigns** [comment]
Hi @barryhughes, thanks so much for your quick response!

For my own purposes, option 2 is the desired functionality, since each duplicated event, occurring on a different date than the original, will need to have its own set of tickets for that specific date/event. This is especially important when considering that each event has limited space. In other words, each event needs separate/unique tickets for inventory management purposes.

I can't imagine a need for option 1, and, again, that's because I don't see the point in duplicating an event unless it will be occurring on a different date.

The major issue I see with duplicating tickets (option 1), is dealing with the ticket SKUs if they've been configured for the original event's ticket/s. I can envision a couple solutions for that:

1. Appending a '-00', '-01', '-02' to the original ticket SKUs might work, but that would require that the duplicator plugin keep track of how many times an event is duplicated, and may produce undesirable SKU formats.
2. Perhaps the SKU, if it exists, would just be cleared, requiring the admin to open the event and edit the tickets if they want to apply a unique SKU for the duplicated event's tickets.
3. Rewriting the SKU could be part of the duplicator's dialogue window, i.e. "New Title: ______", "New Date: ______", and then for each ticket (if tickets exist) "New {ticket-name} SKU: ______". In that same line of thinking, it would be great to also have an option to enter the number of tickets for each ticket type in the duplicator dialogue, just in case, for example, the August event only has 200 seats, where as the same event in September has 250 seats.


While we're on the subject of the duplicator dialogue options/prompts, I think one major feature that is missing from the current options is entering a new url/slug. I absolutely LOVE the options to enter a new event Title and assign a new start date, but the default WP behavior when duplicating a post is to simply append a number to the end of the original slug: `/{old-slug}-1/`, which is not always the desired result. It would be great to also have the opportunity to re-write the slug for a duplicated event.

Thanks again for your response and enthusiasm.

Let me know what you think.

**Comment by barryhughes** [comment]
Sounds great on all counts (and a nice observation re SKUs ... depending on how inventory is stored, that may also require special handling). 

What I can't guarantee is how quickly I can get through all this, but I did want to improve the duplicator in any case (and allow multiple duplicates with different dates/times to be set) so this could certainly tie in as one piece of a broader set of improvements to event duplication :-)

**Comment by adaptifyDesigns** [comment]
Awesome. Looking forward to the enhancements!

I love the idea of having the option to do multiple duplicates at once, all with unique dates. That would be extremely useful.

Thanks for your great work already.

**Comment by barryhughes** [comment]
It may be that the ticketing framework provided by The Events Calendar is re-tooled in the near future, so I'm not going to take this forward right at this time.

**Comment by adaptifyDesigns** [comment]
roger that. thanks for the interest and the work you've already done!
