### ISSUE TITLE
Date/Time-format in the Duplicator

### ISSUE THREAD

**Issue by Scors0** [barryhughes/event-rocket#44]
When duplicating an event with the Java-popup, I can choose another date. Great. I can use the Date Picker, which works brilliantly. However, when I want to type the date, it's all wonky. Reason is that the date format is in US (I suppose?) format (=m/d/Y), whilest I use the European format (=d/m/Y).

If you'd be so kind to make an adjustment so it takes the standard date format set by the Wordpress settings.

**Comment by barryhughes** [comment]
> If you'd be so kind to make an adjustment so it takes the standard date format set by the Wordpress settings.

Probably not, at least not without a huge amount of effort. However, we can definitely follow one of these routes:

* We can have it use a generic, non-regional format like `yyyy-mm-dd`
* We could potentially make it respect the datepicker format set in The Events Calendar settings

**Comment by barryhughes** [comment]
So for the time being I'm going to opt for a generic `yyyy-mm-dd` format as the default. However, I've left it open for users to customize. So long as you follow the expected date format conventions for the jQuery UI library you can change it to pretty much anything you would like, ie:

``` php
/** @see http://api.jqueryui.com/datepicker/#option-dateFormat */
add_filter( 'eventrocket_duplicator_js_datepicker_format', function() {
    return 'mm/dd/yy';
} );
```

This change will roll out as part of 3.3.
