### ISSUE TITLE
"Export Listed Event" ical download incorrect when main events page used as front page

### ISSUE THREAD

**Issue by sokratesagogo** [barryhughes/event-rocket#50]
Hi, 

I'm using the main events page as the front page (set via Settings > Reading) and the iCal file download from the "Export Listed Event" on this page is either blank or lists standard WordPress posts rather than Events.

I've replicated this behaviour on a site with only The Events Calendar, Events Calendar Pro and Event Rocket plugin active.

**Comment by barryhughes** [comment]
Sorry for the very slow response, @sokratesagogo - I haven't actively been monitoring the issue tracker (and in fact will now close it to prevent any further confusion).

I'm afraid Event Rocket is not something I'll be developing further and can only recommend finding and fixing the problem yourself or else moving on to a new solution. Sorry!
